# Generated by Django 3.0.4 on 2020-03-13 15:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Banglore', 'Banglore')], default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='userdata',
            name='decr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='id_proof',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='pincode',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d[0123456789]{5}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='show_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d[0123456789]{9}$')]),
        ),
        migrations.CreateModel(
            name='TutorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorcor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.CharField(max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_id', models.ManyToManyField(blank=True, related_name='Course', to='accounts.TutorCourse')),
                ('student', models.ManyToManyField(blank=True, related_name='enrolled_students', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ManyToManyField(blank=True, related_name='Course_Tutors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
