# Generated by Django 3.0.4 on 2020-03-29 11:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200313_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='id_proof',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='pincode',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d[0123456789]{5}$')]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='show_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
