# Generated by Django 3.0.3 on 2020-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200224_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_url',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
